import os

YOUTUBE_CLIENT_ID = os.environ['YOUTUBE_CLIENT_ID']
YOUTUBE_CLIENT_SECRET = os.environ['YOUTUBE_CLIENT_SECRET']
YOUTUBE_ACCESS_TOKEN = os.environ['YOUTUBE_ACCESS_TOKEN']
SAVED_STATE_PATH = 'state.yaml'
